name: Deploy Lambda To Aws
on:
  push:
    branches:
      - main
jobs:
  Package-And-Deploy-Lambda-Function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
      
      - name: Create lambda.zip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .
          zip -r lambda.zip * -x "bin/*" requirements.txt setup.cfg

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: .
          label: Twitter Bot
          auto_approve: true
          variables: |
            AWS_ACCESS_KEY="${{secrets.AWS_ACCESS_KEY}}"
            AWS_SECRET_KEY="${{secrets.AWS_SECRET_KEY}}"
            TWITTER_ACCESS_TOKEN="${{secrets.TWITTER_ACCESS_TOKEN}}"
            TWITTER_ACCESS_TOKEN_SECRET="${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}"
            TWITTER_CONSUMER_API_KEY="${{secrets.TWITTER_CONSUMER_API_KEY}}"
            TWITTER_CONSUMER_API_SECRET="${{secrets.TWITTER_CONSUMER_API_SECRET}}"
          backend_config: |
            access_key="${{ secrets.AWS_ACCESS_KEY }}"
            secret_key="${{ secrets.AWS_SECRET_KEY }}"
            bucket = "fmtfstatebucket"
            key    = "tfstate"
            region = "eu-north-1"


