name: Deploy Lambda To Aws
on: [push]
jobs:
  Package-Lambda-Function:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.
      
      - name: Create lambda.zip
        run: python -m pip install --upgrade pip
        run: pip install -r requirements.txt -t .
        run: zip -r lambda.zip * -x "bin/*" requirements.txt setup.cfg
        run: ls -la