name: Create terraform plan

on: [pull_request]

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for an example terraform configuration
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create lambda.zip
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .
          zip -r lambda.zip * -x "bin/*" requirements.txt setup.cfg

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: .
          label: Twitter Bot
          variables: |
            AWS_ACCESS_KEY="${{secrets.AWS_ACCESS_KEY}}"
            AWS_SECRET_KEY="${{secrets.AWS_SECRET_KEY}}"
            TWITTER_ACCESS_TOKEN="${{secrets.TWITTER_ACCESS_TOKEN}}"
            TWITTER_ACCESS_TOKEN_SECRET="${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}"
            TWITTER_CONSUMER_API_KEY="${{secrets.TWITTER_CONSUMER_API_KEY}}"
            TWITTER_CONSUMER_API_SECRET="${{secrets.TWITTER_CONSUMER_API_SECRET}}"
